import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  FaRobot, FaCheckCircle, FaDownload, 
  FaUserEdit, FaFileAlt, FaMagic, FaChartLine 
} from 'react-icons/fa';
import { useAuth } from '../context/AuthContext';

const Landing = () => {
  const { user } = useAuth();

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.6, ease: 'easeOut' } }
  };

  return (
    <div className="overflow-x-hidden min-h-screen">
      {/* Background gradients */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[600px] pointer-events-none overflow-hidden z-0 opacity-40 dark:opacity-20">
        <div className="absolute top-[-10%] left-[10%] w-[300px] h-[300px] rounded-full bg-primary blur-[120px]"></div>
        <div className="absolute top-[20%] right-[10%] w-[250px] h-[250px] rounded-full bg-secondary blur-[100px]"></div>
      </div>

      {/* Hero Section */}
      <section className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-24 md:pt-32 md:pb-32">
        <motion.div 
          className="text-center max-w-4xl mx-auto"
          initial="hidden"
          animate="visible"
          variants={containerVariants}
        >
          <motion.div 
            variants={itemVariants}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary dark:text-secondary text-sm font-semibold mb-6 font-poppins"
          >
            <FaRobot className="animate-pulse" /> AI-Powered Resume Builder
          </motion.div>

          <motion.h1 
            variants={itemVariants}
            className="text-4xl sm:text-6xl font-extrabold font-poppins text-brandText-light dark:text-brandText-dark tracking-tight leading-none mb-6"
          >
            Build Professional <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">ATS-Friendly</span> Resumes with AI
          </motion.h1>

          <motion.p 
            variants={itemVariants}
            className="text-lg sm:text-xl text-brandTextSecondary-light dark:text-brandTextSecondary-dark max-w-2xl mx-auto mb-10 leading-relaxed font-inter"
          >
            Land more interviews with a polished, luxury-grade resume optimized for applicant tracking systems. Generated by Google Gemini AI in seconds.
          </motion.p>

          <motion.div 
            variants={itemVariants}
            className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16"
          >
            <Link 
              to={user ? "/dashboard" : "/register"}
              className="premium-btn w-full sm:w-auto text-white bg-primary hover:bg-primary-dark shadow-glass hover:shadow-premium-hover"
            >
              Start Building Free
            </Link>
            <Link 
              to={user ? "/ats-checker" : "/login"}
              className="premium-btn w-full sm:w-auto text-brandText-light dark:text-brandText-dark bg-white dark:bg-brandCard-dark border border-brandBorder-light dark:border-brandBorder-dark hover:bg-black/5 dark:hover:bg-white/5 shadow-premium"
            >
              Analyze Your Resume
            </Link>
          </motion.div>
        </motion.div>

        {/* Live Preview Cards (Floating Resume elements) */}
        <motion.div 
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6, duration: 0.8 }}
          className="relative max-w-4xl mx-auto mt-8 flex justify-center"
        >
          <div className="w-full aspect-[16/9] rounded-2xl glass-card border border-brandBorder-light dark:border-brandBorder-dark shadow-premium overflow-hidden p-6 flex flex-col justify-between">
            {/* Header Mock */}
            <div className="flex justify-between items-start border-b border-brandBorder-light dark:border-brandBorder-dark pb-4">
              <div>
                <div className="h-6 w-48 bg-primary/20 rounded mb-2"></div>
                <div className="h-4 w-32 bg-brandTextSecondary-light/20 rounded"></div>
              </div>
              <div className="h-8 w-24 bg-secondary/20 rounded-full flex items-center justify-center text-xs font-bold text-secondary">ATS Score: 98%</div>
            </div>
            {/* Body Mock */}
            <div className="grid grid-cols-3 gap-6 py-4 flex-1">
              <div className="col-span-2 space-y-3">
                <div className="h-4 w-full bg-brandTextSecondary-light/10 rounded"></div>
                <div className="h-4 w-5/6 bg-brandTextSecondary-light/10 rounded"></div>
                <div className="h-4 w-4/6 bg-brandTextSecondary-light/10 rounded"></div>
                <div className="pt-2 space-y-2">
                  <div className="h-5 w-24 bg-primary/10 rounded"></div>
                  <div className="h-4 w-full bg-brandTextSecondary-light/10 rounded"></div>
                </div>
              </div>
              <div className="col-span-1 space-y-2 border-l border-brandBorder-light dark:border-brandBorder-dark pl-6">
                <div className="h-5 w-16 bg-secondary/10 rounded"></div>
                <div className="flex flex-wrap gap-1">
                  <div className="h-5 w-12 bg-primary/10 rounded"></div>
                  <div className="h-5 w-16 bg-primary/10 rounded"></div>
                  <div className="h-5 w-10 bg-primary/10 rounded"></div>
                </div>
              </div>
            </div>
            {/* Footer Mock */}
            <div className="h-4 w-full bg-brandBorder-light dark:bg-brandBorder-dark/40 rounded"></div>
          </div>

          {/* Floating cards */}
          <div className="absolute -top-12 -left-8 md:-left-16 w-48 bg-white dark:bg-brandCard-dark p-4 rounded-xl border border-brandBorder-light dark:border-brandBorder-dark shadow-premium-hover floating-card-1 hidden sm:block">
            <div className="flex items-center gap-2 mb-2">
              <span className="h-2 w-2 rounded-full bg-green-500"></span>
              <span className="text-xs font-semibold font-poppins text-brandText-light dark:text-brandText-dark">AI Optimized</span>
            </div>
            <p className="text-[10px] text-brandTextSecondary-light dark:text-brandTextSecondary-dark">Summary optimized with impact verbs & industry keywords.</p>
          </div>

          <div className="absolute -bottom-6 -right-8 md:-right-16 w-52 bg-white dark:bg-brandCard-dark p-4 rounded-xl border border-brandBorder-light dark:border-brandBorder-dark shadow-premium-hover floating-card-2 hidden sm:block">
            <div className="flex items-center gap-2 mb-2">
              <span className="h-4 w-4 rounded bg-primary/10 flex items-center justify-center text-primary text-[10px] font-bold">JD</span>
              <span className="text-xs font-semibold font-poppins text-brandText-light dark:text-brandText-dark">Job Match Success</span>
            </div>
            <div className="w-full bg-gray-200 dark:bg-gray-700 h-2 rounded-full overflow-hidden">
              <div className="bg-primary h-full rounded-full" style={{ width: '92%' }}></div>
            </div>
            <span className="text-[10px] mt-1 block text-right font-medium text-brandTextSecondary-light dark:text-brandTextSecondary-dark">92% Compatibility</span>
          </div>
        </motion.div>
      </section>

      {/* Feature Section */}
      <section className="bg-white dark:bg-brandCard-dark border-y border-brandBorder-light dark:border-brandBorder-dark py-24 transition-colors duration-300">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="text-3xl font-bold font-poppins mb-4">State-of-the-Art Core Features</h2>
            <p className="text-brandTextSecondary-light dark:text-brandTextSecondary-dark">Everything you need to craft an outstanding application and fast-track your career goals.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="p-6 rounded-2xl border border-brandBorder-light dark:border-brandBorder-dark hover:shadow-premium-hover transition-all duration-300">
              <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary mb-6">
                <FaRobot className="text-xl" />
              </div>
              <h3 className="text-xl font-bold font-poppins mb-3">AI Content Generator</h3>
              <p className="text-sm text-brandTextSecondary-light dark:text-brandTextSecondary-dark leading-relaxed">Let Google Gemini write professional summaries, structure bullet points, and suggest industry-specific skills automatically.</p>
            </div>
            <div className="p-6 rounded-2xl border border-brandBorder-light dark:border-brandBorder-dark hover:shadow-premium-hover transition-all duration-300">
              <div className="h-12 w-12 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary mb-6">
                <FaChartLine className="text-xl" />
              </div>
              <h3 className="text-xl font-bold font-poppins mb-3">ATS Score Optimization</h3>
              <p className="text-sm text-brandTextSecondary-light dark:text-brandTextSecondary-dark leading-relaxed">Paste the description of your target job, and our analyzer will scan and match keywords, reporting direct recommendations to beat the bots.</p>
            </div>
            <div className="p-6 rounded-2xl border border-brandBorder-light dark:border-brandBorder-dark hover:shadow-premium-hover transition-all duration-300">
              <div className="h-12 w-12 rounded-xl bg-green-100 dark:bg-green-950/20 flex items-center justify-center text-green-500 mb-6">
                <FaDownload className="text-xl" />
              </div>
              <h3 className="text-xl font-bold font-poppins mb-3">One-Click PDF Export</h3>
              <p className="text-sm text-brandTextSecondary-light dark:text-brandTextSecondary-dark leading-relaxed">Instantly export clean, print-ready, and ATS-friendly PDF templates. Zero watermark, standard A4 scale, formatted flawlessly.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl font-bold font-poppins mb-4">Loved by Modern Job Seekers</h2>
          <p className="text-brandTextSecondary-light dark:text-brandTextSecondary-dark">See how candidates landed jobs at Stripe, Notion, Google, and Canva using Resume AI.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-8 rounded-2xl bg-white dark:bg-brandCard-dark border border-brandBorder-light dark:border-brandBorder-dark shadow-premium">
            <p className="text-brandTextSecondary-light dark:text-brandTextSecondary-dark italic mb-6">"Using this tool was a game changer. The AI summary generation captured my exact skills perfectly and quantified my project impact. I got an interview offer at Stripe within a week!"</p>
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 bg-primary/20 rounded-full flex items-center justify-center font-bold text-primary font-poppins">SL</div>
              <div>
                <h4 className="font-bold text-sm text-brandText-light dark:text-brandText-dark">Sarah Lang</h4>
                <p className="text-xs text-brandTextSecondary-light dark:text-brandTextSecondary-dark">Senior Product Engineer</p>
              </div>
            </div>
          </div>
          <div className="p-8 rounded-2xl bg-white dark:bg-brandCard-dark border border-brandBorder-light dark:border-brandBorder-dark shadow-premium">
            <p className="text-brandTextSecondary-light dark:text-brandTextSecondary-dark italic mb-6">"The ATS Checker is incredibly accurate. It helped me realize I missed 5 key skill keywords required by the job posting. Replaced them, raised my score to 95%, and got the callback."</p>
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 bg-secondary/20 rounded-full flex items-center justify-center font-bold text-secondary font-poppins">JM</div>
              <div>
                <h4 className="font-bold text-sm text-brandText-light dark:text-brandText-dark">Jason Miller</h4>
                <p className="text-xs text-brandTextSecondary-light dark:text-brandTextSecondary-dark">Staff Designer</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-r from-primary to-secondary py-20 text-white text-center">
        <div className="max-w-4xl mx-auto px-4">
          <h2 className="text-3xl sm:text-5xl font-extrabold font-poppins mb-6">Ready to land your dream job?</h2>
          <p className="text-lg mb-10 max-w-xl mx-auto opacity-90">Create your premium account today and access unlimited ATS resume iterations, AI generations, and cover letters.</p>
          <Link 
            to={user ? "/dashboard" : "/register"}
            className="px-8 py-4 font-poppins font-semibold bg-white text-primary rounded-xl hover:shadow-premium-hover transition-all duration-300 inline-block"
          >
            Get Started For Free
          </Link>
        </div>
      </section>
    </div>
  );
};

export default Landing;
